# Generated by Django 5.1.7 on 2025-03-26 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_threads', models.IntegerField(default=0)),
                ('total_threads', models.IntegerField(default=0)),
                ('progress', models.FloatField(default=0.0)),
                ('status', models.CharField(default='not_started', max_length=50)),
                ('auto_parse_enabled', models.BooleanField(default=False, verbose_name='Автоматический парсинг включен')),
                ('auto_parse_interval', models.PositiveIntegerField(default=60, verbose_name='Интервал (минуты)')),
                ('auto_parse_pages', models.PositiveIntegerField(default=1, verbose_name='Количество страниц')),
                ('next_parse_time', models.DateTimeField(blank=True, null=True, verbose_name='Время следующего запуска')),
            ],
        ),
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('last_parsed_at', models.DateTimeField(blank=True, null=True)),
                ('leading_judge', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ведущий судья')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='web_forumth_created_ad3ff8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ThreadMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('author', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('posted_at', models.DateTimeField(db_index=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='web.forumthread')),
            ],
            options={
                'indexes': [models.Index(fields=['posted_at'], name='web_threadm_posted__b270b2_idx')],
            },
        ),
    ]
