# Generated by Django 5.1.7 on 2025-03-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseprogress',
            name='auto_parse_enabled',
            field=models.BooleanField(default=False, verbose_name='Автоматический парсинг включен'),
        ),
        migrations.AddField(
            model_name='parseprogress',
            name='auto_parse_interval',
            field=models.PositiveIntegerField(default=60, verbose_name='Интервал (минуты)'),
        ),
        migrations.AddField(
            model_name='parseprogress',
            name='auto_parse_pages',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество страниц'),
        ),
    ]
