# Generated by Django 5.1.7 on 2025-03-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_parseprogress_auto_parse_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseprogress',
            name='next_parse_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время следующего запуска'),
        ),
    ]
