# Generated by Django 5.1.7 on 2025-03-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_forumthread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='last_parsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
