# Generated by Django 5.1.7 on 2025-03-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_forumthread_last_parsed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='leading_judge',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ведущий судья'),
        ),
    ]
