# Generated by Django 5.1.7 on 2025-03-24 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('forum_account', models.CharField(max_length=100, verbose_name='Форумный аккаунт')),
                ('discord_id', models.CharField(blank=True, max_length=100, verbose_name='ID Discord')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительно')),
            ],
            options={
                'verbose_name': 'Судья',
                'verbose_name_plural': 'Судьи',
            },
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateField(verbose_name='Дата приёма на работу')),
                ('dismissal_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='judges.judge', verbose_name='Судья')),
            ],
            options={
                'verbose_name': 'История приёма/увольнения',
                'verbose_name_plural': 'История приёмов/увольнений',
            },
        ),
    ]
