# Generated by Django 5.1.7 on 2025-03-25 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='discord_id',
            field=models.CharField(blank=True, max_length=18, validators=[django.core.validators.RegexValidator('^\\d{17,18}$', 'Неверный формат ID Discord')], verbose_name='ID Discord'),
        ),
        migrations.AddIndex(
            model_name='judge',
            index=models.Index(fields=['forum_account'], name='judges_judg_forum_a_b8cbdc_idx'),
        ),
    ]
